# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mi_formulario.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(707, 458)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 691, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.AgregarP = QtWidgets.QPushButton(self.frame)
        self.AgregarP.setGeometry(QtCore.QRect(520, 160, 151, 28))
        self.AgregarP.setObjectName("AgregarP")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 121, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(24, 70, 81, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(24, 120, 81, 20))
        self.label_3.setObjectName("label_3")
        self.DocID = QtWidgets.QLineEdit(self.frame)
        self.DocID.setGeometry(QtCore.QRect(170, 20, 151, 22))
        self.DocID.setObjectName("DocID")
        self.Nom = QtWidgets.QLineEdit(self.frame)
        self.Nom.setGeometry(QtCore.QRect(170, 70, 151, 22))
        self.Nom.setObjectName("Nom")
        self.Cel = QtWidgets.QLineEdit(self.frame)
        self.Cel.setGeometry(QtCore.QRect(170, 120, 151, 22))
        self.Cel.setObjectName("Cel")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(350, 70, 51, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(350, 120, 51, 20))
        self.label_5.setObjectName("label_5")
        self.Mail = QtWidgets.QLineEdit(self.frame)
        self.Mail.setGeometry(QtCore.QRect(420, 120, 151, 22))
        self.Mail.setObjectName("Mail")
        self.Apellido = QtWidgets.QLineEdit(self.frame)
        self.Apellido.setGeometry(QtCore.QRect(420, 70, 151, 22))
        self.Apellido.setObjectName("Apellido")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 230, 691, 221))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.DocID_2 = QtWidgets.QLineEdit(self.frame_2)
        self.DocID_2.setGeometry(QtCore.QRect(110, 40, 151, 22))
        self.DocID_2.setObjectName("DocID_2")
        self.DocID_3 = QtWidgets.QLineEdit(self.frame_2)
        self.DocID_3.setGeometry(QtCore.QRect(110, 90, 151, 22))
        self.DocID_3.setObjectName("DocID_3")
        self.DocID_4 = QtWidgets.QLineEdit(self.frame_2)
        self.DocID_4.setGeometry(QtCore.QRect(410, 40, 151, 22))
        self.DocID_4.setObjectName("DocID_4")
        self.AgregarP_2 = QtWidgets.QPushButton(self.frame_2)
        self.AgregarP_2.setGeometry(QtCore.QRect(520, 170, 151, 28))
        self.AgregarP_2.setObjectName("AgregarP_2")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 41, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(20, 90, 61, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(290, 40, 91, 20))
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.AgregarP.setText(_translate("Dialog", "Agregar Propietario"))
        self.label.setText(_translate("Dialog", "Documento Identidad"))
        self.label_2.setText(_translate("Dialog", "Nombre"))
        self.label_3.setText(_translate("Dialog", "Tel/Cel"))
        self.label_4.setText(_translate("Dialog", "Apellido"))
        self.label_5.setText(_translate("Dialog", "Correo"))
        self.AgregarP_2.setText(_translate("Dialog", "Agregar Finca"))
        self.label_6.setText(_translate("Dialog", "Cultivo"))
        self.label_7.setText(_translate("Dialog", "Municipio"))
        self.label_8.setText(_translate("Dialog", "Registro Castral"))
